### ISSUE TITLE
touch: cannot touch '/etc/cranberry-test': Read-only file system

### ISSUE THREAD

**Issue by yefoenix** [CerisWhite/CrAnberry#20]
![Screenshot 2021-11-18 00 03 02](https://user-images.githubusercontent.com/8215230/142236448-93c84f95-064b-49f2-a6ad-e651bc9122f0.png)
![Screenshot 2021-11-17 23 54 24](https://user-images.githubusercontent.com/8215230/142236484-1400f0fb-2dbc-4ca5-a5f9-4fda9461a459.png)
My Device: Pixelbook Eve
ChromeOS version:96.0.4664.51 beta
Android Version : 9

**Comment by supechicken** [comment]
You need to remount your rootfs to read/write in order to make changes to the Android container image
```
sudo mount -o remount,rw /
```

**Comment by yefoenix** [comment]
it feedback:
> mount: /: cannot remount /dev/dm-0 read-write, is write-protected.
![Screenshot 2021-11-18 00 24 52](https://user-images.githubusercontent.com/8215230/142240671-138d9a81-f1df-449e-b73f-979f9daf0378.png)

**Comment by supechicken** [comment]
Try again after reboot?

**Comment by yefoenix** [comment]
> Try again after reboot?

it works after reboot,thansk a lot!
