### ISSUE TITLE
No android system image present in /opt/google/containers/android/

### ISSUE THREAD

**Issue by zhaomo123** [CerisWhite/CrAnberry#21]
I'm a Chinese,and my english is not good now.
Show this after running,how to fix it?
No android system image present in /opt/google/containers/android/

**Comment by CerisWhite** [comment]
If you do not have the android subsystem available, this script will not work for you.

**Comment by zylenox2** [comment]
![Screenshot 2023-12-04 12 30 37](https://github.com/CerisWhite/CrAnberry/assets/121976812/a5e1967e-c601-423a-96e7-3701745f0f0c)
but...

**Comment by CerisWhite** [comment]
Due to recent system changes (which you can read right there in the window), you can't use `sudo` for root access in the crosh terminal anymore without a custom-built image. You'll have to run the script from VT2. This script requires `sudo` to do what it does, so there's no other way.

**Comment by zylenox2** [comment]
Yes, I managed to accomplish that. The issue I'm having is that it says there is no android system image present in the top left but in the bottom right you can clearly see that there is.

**Comment by CerisWhite** [comment]
It's saying that in the crosh shell, because the script can't access the files without root.
