### ISSUE TITLE
After execute the script without errors and reboot, all data on /opt/google/containers/android/rootfs/root/ is deleted

### ISSUE THREAD

**Issue by kasuki92** [CerisWhite/CrAnberry#25]
The script runs without problems, the policy file is correctly patched with supersu and in /opt/google/containers/android/rootfs/root/system/xbin are all the necessary binaries, but after reboot, the directory /opt/google/containers/android/rootfs/root/ is left empty. I don't know why this happens, I need some help.

**Comment by CerisWhite** [comment]
I'll need you to provide the following information to work with this issue: 
Your ChromeOS version
The version of Android running on your system
The CPU architecture of your device

**Comment by CerisWhite** [comment]
Since there has been no reply, I'm going to close this as stale.
