### ISSUE TITLE
i need help(: 

### ISSUE THREAD

**Issue by IIIMGHIII** [CerisWhite/CrAnberry#26]
chronos@localhost / $ curl https://raw.githubusercontent.com/CerisWhite/CrAnberry/main/cranberry.sh | sudo bash

0+0 records in
0+0 records out
0 bytes copied, 2.1442e-05 s, 0.0 kB/s
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks: done                            
Creating filesystem with 384000 4k blocks and 96000 inodes
Filesystem UUID: a389f001-9ef7-4489-b2e9-bd3285382d7b
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done 

SELinux set to Permissive.
 
Copying files into new android image
Errors about acct, dev, or oem are normal

*i used it on FydeOS

**Comment by CerisWhite** [comment]
This issue is lacking any form of documentation to work with. What error occurred? I see nothing wrong with what you've pasted here.
