### ISSUE TITLE
Chrome Os is upgrading to a different version of arm.

### ISSUE THREAD

**Issue by chinh4thepro** [CerisWhite/CrAnberry#7]
I'm currently in their beta and they started supporting arm v8 applications and I feel like you guys should try upgrading it.

**Comment by CerisWhite** [comment]
I do not have an ARMv8 device, and don't intend to get one myself. If someone is willing to work as a test subject, I'd be glad to update this to correct any issues ARMv8 may experience, but as far as I can tell, this should work fine regardless. The binaries it uses are ARM32 for compatibility reasons and that shouldn't break unless they begin shipping pure-64bit images.
